/** Uma curiosidade por seleção para exibir na sidebar de palpites. */
export const TEAM_CURIOSITIES: Record<string, string> = {
  MEX: 'O México disputa sua 17ª Copa do Mundo, sendo a seleção da CONCACAF com mais participações na história.',
  RSA: 'A África do Sul foi a primeira nação africana a sediar uma Copa do Mundo, em 2010, tornando o vuvuzela famoso.',
  KOR: 'A Coreia do Sul é o único país asiático a ter chegado às semifinais de uma Copa do Mundo — feito de 2002.',
  CZE: 'A Tchecoslováquia, predecessora da Tchéquia, foi vice-campeã mundial em 1934 e 1962.',
  CAN: 'O Canadá voltou à Copa em 2022 após 36 anos de ausência e agora é co-sede do Mundial de 2026.',
  BIH: 'A Bósnia e Herzegovina estreou em Copas em 2014, marcando seu primeiro gol contra a Argentina de Messi.',
  QAT: 'O Qatar foi o primeiro anfitrião eliminado na fase de grupos, mas deixou estádios climatizados no deserto como legado.',
  SUI: 'A Suíça ficou 35 anos fora das Copas (1966–1994), mas desde 2006 se classificou para todas as edições.',
  BRA: 'O Brasil é o único país a disputar todas as 22 edições da Copa do Mundo — e é o pentacampeão mundial.',
  MAR: 'O Marrocos foi a primeira seleção africana e árabe a atingir as semifinais de uma Copa do Mundo, em 2022.',
  HAI: 'O Haiti disputou sua única Copa do Mundo em 1974, na Alemanha, representando o futebol caribenho no mundo.',
  SCO: 'A Escócia participou do primeiro jogo internacional da história do futebol, em 1872 contra a Inglaterra.',
  USA: 'Os Estados Unidos surpreenderam o mundo chegando às semifinais da primeira Copa do Mundo, em 1930 no Uruguai.',
  PAR: 'O Paraguai ficou invicto por 5 jogos na Copa de 2010 antes de cair nas quartas de final diante da Espanha.',
  AUS: 'A Austrália teve sua melhor Copa em 2006, chegando às oitavas com Tim Cahill como grande destaque.',
  TUR: 'Hakan Şükür marcou o gol mais rápido da história das Copas: apenas 11 segundos na disputa do 3º lugar em 2002.',
  GER: 'A Alemanha é a única seleção com 4 títulos mundiais e nunca foi eliminada na fase de grupos de uma Copa.',
  CUW: 'Curaçao estreia em sua primeira Copa do Mundo em 2026, representando uma ilha caribenha de apenas 160 mil habitantes.',
  CIV: 'A Costa do Marfim teve Didier Drogba como símbolo de uma geração dourada que chegou às oitavas em 2006 e 2010.',
  ECU: 'O Equador venceu a Polônia de Lewandowski na abertura da Copa de 2022 — sua melhor atuação em Mundiais.',
  NED: 'A Holanda perdeu três finais de Copa (1974, 1978 e 2010), o recorde de finais sem título da história.',
  JPN: 'O Japão é o único país asiático classificado para 8 Copas do Mundo consecutivas desde 1998.',
  SWE: 'A Suécia foi vice-campeã na Copa de 1958, disputada no Brasil, derrotada por uma equipe com o jovem Pelé.',
  TUN: 'A Tunísia foi a primeira seleção africana a vencer uma partida em uma Copa do Mundo, em 1978 contra o México.',
  BEL: 'A Bélgica terminou em 3º lugar na Copa de 2018 com Hazard, De Bruyne e Lukaku — geração mais talentosa de sua história.',
  EGY: 'O Egito foi o primeiro país africano a disputar uma Copa do Mundo, em 1934 na Itália.',
  IRN: 'O Irã tem o maior estádio do Oriente Médio — o Azadi Stadium, com 100 mil lugares — e já disputou 7 Copas.',
  NZL: 'A Nova Zelândia foi a única seleção a terminar uma Copa invicta sem avançar — empatou todos os 3 jogos em 2010.',
  ESP: 'A Espanha foi a primeira seleção europeia a vencer a Copa fora da Europa, conquistando o título em 2010 na África do Sul.',
  CPV: 'Cabo Verde estreia em sua primeira Copa do Mundo em 2026, representando um arquipélago de apenas 500 mil habitantes.',
  KSA: 'A Arábia Saudita causou uma das maiores zebras das Copas ao vencer a Argentina de Messi por 2 a 1 em 2022.',
  URU: 'O Uruguai é o campeão da primeira Copa do Mundo da história, realizada em 1930 em seu próprio país.',
  FRA: 'A França é a única seleção bicampeã (1998 e 2018) a ter sido eliminada na fase de grupos na edição seguinte.',
  SEN: 'O Senegal chegou às quartas de final em sua estreia em 2002, eliminando os então campeões mundiais da França.',
  IRQ: 'O Iraque conquistou sua única Copa Asiática em 2007 e retorna a uma Copa do Mundo após décadas de ausência.',
  NOR: 'A Noruega nunca perdeu para o Brasil em Copas do Mundo — e essa conta inclui uma vitória por 4 a 1 em 1998.',
  ARG: 'A Argentina de Messi conquistou o tricampeonato em 2022, 36 anos após o bicampeonato da era Maradona.',
  ALG: 'A Argélia chegou às oitavas de final em 2014 e quase eliminou a Alemanha — jogo foi para prorrogação.',
  AUT: 'A Áustria ficou em 3º lugar na Copa de 1954 e retorna a um Mundial em 2026 após longa ausência.',
  JOR: 'A Jordânia estreia em sua primeira Copa do Mundo em 2026, consolidando o crescimento do futebol árabe.',
  COL: 'James Rodríguez foi o artilheiro da Copa de 2014 com 6 gols, levando a Colômbia às quartas de final.',
  CRO: 'A Croácia foi finalista em 2018 e 3ª colocada em 2022 — com Modric sendo eleito o melhor jogador do mundo.',
  GHA: 'Gana é a seleção africana que mais vezes alcançou as quartas de final de uma Copa do Mundo — duas vezes.',
  PAN: 'O Panamá disputou sua primeira Copa em 2018, marcando o primeiro gol da história da seleção num Mundial.',
  POR: 'Portugal tem Cristiano Ronaldo como artilheiro histórico das Eliminatórias Europeias, mas ainda busca seu primeiro título.',
  COD: 'A RD Congo (ex-Zaire) foi a primeira seleção da África Subsaariana a disputar uma Copa do Mundo, em 1974.',
  ENG: 'A Inglaterra inventou o futebol associação moderno e conquistou seu único título mundial em 1966, em casa.',
  UZB: 'O Uzbequistão estreia em sua primeira Copa do Mundo em 2026, sendo a grande surpresa das Eliminatórias Asiáticas.',
};

export function getCuriosity(teamCode: string): string | null {
  return TEAM_CURIOSITIES[teamCode] ?? null;
}
